import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Lobster } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable:'--font-roboto',
  weight:["100","300", '400',  ],
  subsets:["latin"],
})

const lobster = Lobster({
  weight:"400"
})

export const metadata: Metadata = {
  title: "R. Renn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} m-2 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
