import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";



const roboto = Roboto({
  variable:'--font-roboto',
  weight:["100","300", '400',  ],
  subsets:["latin"],
})



export const metadata: Metadata = {
  title: "R. Renn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} m-2 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
